org 0000h
//IMMEDIATE ADDRESSING MODE
MOV A, #55H;

//REGISTER ADDRESSING MODE
MOV R0,#88H;
MOV A,R0;  //'MOV R(n),R(n)' is an invalid OPCode

//DIRECT ADDRESSING MODE
MOV R7,10H;

//INDIRECT ADDRESSING MODE
MOV R1,#20H;    // VALUE- 20H IS STORED IN REGISTER R1
MOV A,@R1;    // R1 HAS VALUE 20H, WHICH WILL BE USED AS ADDRESS LOCATION- D:0X0020. THE VALUE STORED AT THIS LOCATION WILL BE MOVED TO REGISTER- A.

END